# Secrets Dex via Vault. Prérequis (une fois) :
# 1. Gitea admin -> Applications -> Create OAuth2 App :
#      Name: dex ; Redirect URI: https://dex.apps.itssolutions.me/callback
# 2. vput kv put secret/dex \
#      gitea-client-id='<ID>' gitea-client-secret='<SECRET>' \
#      backstage-client-secret="$(openssl rand -hex 24)" \
#      argocd-client-secret="$(openssl rand -hex 24)" \
#      grafana-client-secret="$(openssl rand -hex 24)" \
#      harbor-client-secret="$(openssl rand -hex 24)"
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef: {name: vault, kind: ClusterSecretStore}
  target: {name: dex-secrets, creationPolicy: Owner}
  dataFrom:
    - extract: {key: dex}
