apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.*
    helm:
      valuesObject:
        controller:
          service:
            type: LoadBalancer
            loadBalancerIP: 10.10.0.240
            externalTrafficPolicy: Local
          ingressClassResource:
            name: nginx
            default: true
          replicaCount: 2
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: ingress-nginx
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {memory: 512Mi}
          metrics:
            enabled: true
          admissionWebhooks:
            enabled: true
          extraArgs:
            default-ssl-certificate: "ingress-nginx/wildcard-apps-tls"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
